services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_development
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  web:
    build: .
    entrypoint: [ "./entrypoint.sh" ]
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - db
    networks:
      - my_network

volumes:
  mysql_data:


networks:
  my_network:
    driver: bridge
